//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.13 at 03:27:41 PM IST 
//


package com.kraft.pim.step;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BasketType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BasketType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;element name="ClassificationBasketLink" type="{}ClassificationBasketLinkType"/>
 *         &lt;element name="ProductBasketLink" type="{}ProductBasketLinkType"/>
 *         &lt;element name="AssetBasketLink" type="{}AssetBasketLinkType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BasketType", propOrder = {
    "classificationBasketLink",
    "productBasketLink",
    "assetBasketLink"
})
public class BasketType {

    @XmlElement(name = "ClassificationBasketLink")
    protected ClassificationBasketLinkType classificationBasketLink;
    @XmlElement(name = "ProductBasketLink")
    protected ProductBasketLinkType productBasketLink;
    @XmlElement(name = "AssetBasketLink")
    protected AssetBasketLinkType assetBasketLink;

    /**
     * Gets the value of the classificationBasketLink property.
     * 
     * @return
     *     possible object is
     *     {@link ClassificationBasketLinkType }
     *     
     */
    public ClassificationBasketLinkType getClassificationBasketLink() {
        return classificationBasketLink;
    }

    /**
     * Sets the value of the classificationBasketLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassificationBasketLinkType }
     *     
     */
    public void setClassificationBasketLink(ClassificationBasketLinkType value) {
        this.classificationBasketLink = value;
    }

    /**
     * Gets the value of the productBasketLink property.
     * 
     * @return
     *     possible object is
     *     {@link ProductBasketLinkType }
     *     
     */
    public ProductBasketLinkType getProductBasketLink() {
        return productBasketLink;
    }

    /**
     * Sets the value of the productBasketLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductBasketLinkType }
     *     
     */
    public void setProductBasketLink(ProductBasketLinkType value) {
        this.productBasketLink = value;
    }

    /**
     * Gets the value of the assetBasketLink property.
     * 
     * @return
     *     possible object is
     *     {@link AssetBasketLinkType }
     *     
     */
    public AssetBasketLinkType getAssetBasketLink() {
        return assetBasketLink;
    }

    /**
     * Sets the value of the assetBasketLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetBasketLinkType }
     *     
     */
    public void setAssetBasketLink(AssetBasketLinkType value) {
        this.assetBasketLink = value;
    }

}
