//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.13 at 03:27:41 PM IST 
//


package com.kraft.pim.step;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kraft.pim.step package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GUISetupTypeGUISetupAdvanced_QNAME = new QName("", "GUISetupAdvanced");
    private final static QName _GUISetupTypeGUISetupDisabled_QNAME = new QName("", "GUISetupDisabled");
    private final static QName _GUISetupTypeGUISetupEnabled_QNAME = new QName("", "GUISetupEnabled");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kraft.pim.step
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClassificationsType }
     * 
     */
    public ClassificationsType createClassificationsType() {
        return new ClassificationsType();
    }

    /**
     * Create an instance of {@link ListOfValuesGroupListType }
     * 
     */
    public ListOfValuesGroupListType createListOfValuesGroupListType() {
        return new ListOfValuesGroupListType();
    }

    /**
     * Create an instance of {@link GDSNReceiverUnitType }
     * 
     */
    public GDSNReceiverUnitType createGDSNReceiverUnitType() {
        return new GDSNReceiverUnitType();
    }

    /**
     * Create an instance of {@link STEPWorkflowsType }
     * 
     */
    public STEPWorkflowsType createSTEPWorkflowsType() {
        return new STEPWorkflowsType();
    }

    /**
     * Create an instance of {@link CrossContextsType }
     * 
     */
    public CrossContextsType createCrossContextsType() {
        return new CrossContextsType();
    }

    /**
     * Create an instance of {@link TableTypeType }
     * 
     */
    public TableTypeType createTableTypeType() {
        return new TableTypeType();
    }

    /**
     * Create an instance of {@link TransformationLookupTableConfigurationType }
     * 
     */
    public TransformationLookupTableConfigurationType createTransformationLookupTableConfigurationType() {
        return new TransformationLookupTableConfigurationType();
    }

    /**
     * Create an instance of {@link ProductTemplateType }
     * 
     */
    public ProductTemplateType createProductTemplateType() {
        return new ProductTemplateType();
    }

    /**
     * Create an instance of {@link ReplaceProductValuesForAttributeGroupType }
     * 
     */
    public ReplaceProductValuesForAttributeGroupType createReplaceProductValuesForAttributeGroupType() {
        return new ReplaceProductValuesForAttributeGroupType();
    }

    /**
     * Create an instance of {@link TablesType }
     * 
     */
    public TablesType createTablesType() {
        return new TablesType();
    }

    /**
     * Create an instance of {@link SampleFileType }
     * 
     */
    public SampleFileType createSampleFileType() {
        return new SampleFileType();
    }

    /**
     * Create an instance of {@link BulkUpdateConfigurationType }
     * 
     */
    public BulkUpdateConfigurationType createBulkUpdateConfigurationType() {
        return new BulkUpdateConfigurationType();
    }

    /**
     * Create an instance of {@link UnitConversionType }
     * 
     */
    public UnitConversionType createUnitConversionType() {
        return new UnitConversionType();
    }

    /**
     * Create an instance of {@link CommercialListType }
     * 
     */
    public CommercialListType createCommercialListType() {
        return new CommercialListType();
    }

    /**
     * Create an instance of {@link BusinessRuleDescriptionType }
     * 
     */
    public BusinessRuleDescriptionType createBusinessRuleDescriptionType() {
        return new BusinessRuleDescriptionType();
    }

    /**
     * Create an instance of {@link RowTypesType }
     * 
     */
    public RowTypesType createRowTypesType() {
        return new RowTypesType();
    }

    /**
     * Create an instance of {@link IntegrationEndpointsType }
     * 
     */
    public IntegrationEndpointsType createIntegrationEndpointsType() {
        return new IntegrationEndpointsType();
    }

    /**
     * Create an instance of {@link ReplacementRulesType }
     * 
     */
    public ReplacementRulesType createReplacementRulesType() {
        return new ReplacementRulesType();
    }

    /**
     * Create an instance of {@link ClassificationType }
     * 
     */
    public ClassificationType createClassificationType() {
        return new ClassificationType();
    }

    /**
     * Create an instance of {@link DimensionListType }
     * 
     */
    public DimensionListType createDimensionListType() {
        return new DimensionListType();
    }

    /**
     * Create an instance of {@link DimensionPointLinkType }
     * 
     */
    public DimensionPointLinkType createDimensionPointLinkType() {
        return new DimensionPointLinkType();
    }

    /**
     * Create an instance of {@link AttributeTransformationType }
     * 
     */
    public AttributeTransformationType createAttributeTransformationType() {
        return new AttributeTransformationType();
    }

    /**
     * Create an instance of {@link EntitiesType }
     * 
     */
    public EntitiesType createEntitiesType() {
        return new EntitiesType();
    }

    /**
     * Create an instance of {@link SuppressedContextCrossReferenceType }
     * 
     */
    public SuppressedContextCrossReferenceType createSuppressedContextCrossReferenceType() {
        return new SuppressedContextCrossReferenceType();
    }

    /**
     * Create an instance of {@link MissingObjectsType }
     * 
     */
    public MissingObjectsType createMissingObjectsType() {
        return new MissingObjectsType();
    }

    /**
     * Create an instance of {@link TaskType }
     * 
     */
    public TaskType createTaskType() {
        return new TaskType();
    }

    /**
     * Create an instance of {@link TagFormatType }
     * 
     */
    public TagFormatType createTagFormatType() {
        return new TagFormatType();
    }

    /**
     * Create an instance of {@link ValueGroupType }
     * 
     */
    public ValueGroupType createValueGroupType() {
        return new ValueGroupType();
    }

    /**
     * Create an instance of {@link HyperlinkTagGroupType }
     * 
     */
    public HyperlinkTagGroupType createHyperlinkTagGroupType() {
        return new HyperlinkTagGroupType();
    }

    /**
     * Create an instance of {@link DeleteAssetsType }
     * 
     */
    public DeleteAssetsType createDeleteAssetsType() {
        return new DeleteAssetsType();
    }

    /**
     * Create an instance of {@link SystemSetupValueType }
     * 
     */
    public SystemSetupValueType createSystemSetupValueType() {
        return new SystemSetupValueType();
    }

    /**
     * Create an instance of {@link EventQueueType }
     * 
     */
    public EventQueueType createEventQueueType() {
        return new EventQueueType();
    }

    /**
     * Create an instance of {@link DeleteClassificationType }
     * 
     */
    public DeleteClassificationType createDeleteClassificationType() {
        return new DeleteClassificationType();
    }

    /**
     * Create an instance of {@link ECatalogType }
     * 
     */
    public ECatalogType createECatalogType() {
        return new ECatalogType();
    }

    /**
     * Create an instance of {@link UserListType }
     * 
     */
    public UserListType createUserListType() {
        return new UserListType();
    }

    /**
     * Create an instance of {@link TermsListLinkType }
     * 
     */
    public TermsListLinkType createTermsListLinkType() {
        return new TermsListLinkType();
    }

    /**
     * Create an instance of {@link SetupGroupsType }
     * 
     */
    public SetupGroupsType createSetupGroupsType() {
        return new SetupGroupsType();
    }

    /**
     * Create an instance of {@link UserTypeLinkType }
     * 
     */
    public UserTypeLinkType createUserTypeLinkType() {
        return new UserTypeLinkType();
    }

    /**
     * Create an instance of {@link ReplaceProductToProductCrossReferenceType }
     * 
     */
    public ReplaceProductToProductCrossReferenceType createReplaceProductToProductCrossReferenceType() {
        return new ReplaceProductToProductCrossReferenceType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link OverrideSubProductType }
     * 
     */
    public OverrideSubProductType createOverrideSubProductType() {
        return new OverrideSubProductType();
    }

    /**
     * Create an instance of {@link OutBoundIntegrationEndpointType }
     * 
     */
    public OutBoundIntegrationEndpointType createOutBoundIntegrationEndpointType() {
        return new OutBoundIntegrationEndpointType();
    }

    /**
     * Create an instance of {@link AssetBasketLinkType }
     * 
     */
    public AssetBasketLinkType createAssetBasketLinkType() {
        return new AssetBasketLinkType();
    }

    /**
     * Create an instance of {@link SystemSetupType }
     * 
     */
    public SystemSetupType createSystemSetupType() {
        return new SystemSetupType();
    }

    /**
     * Create an instance of {@link UserTypeType }
     * 
     */
    public UserTypeType createUserTypeType() {
        return new UserTypeType();
    }

    /**
     * Create an instance of {@link ContextType }
     * 
     */
    public ContextType createContextType() {
        return new ContextType();
    }

    /**
     * Create an instance of {@link ExportConfigurationType }
     * 
     */
    public ExportConfigurationType createExportConfigurationType() {
        return new ExportConfigurationType();
    }

    /**
     * Create an instance of {@link DeleteProductCrossReferenceType }
     * 
     */
    public DeleteProductCrossReferenceType createDeleteProductCrossReferenceType() {
        return new DeleteProductCrossReferenceType();
    }

    /**
     * Create an instance of {@link TermType }
     * 
     */
    public TermType createTermType() {
        return new TermType();
    }

    /**
     * Create an instance of {@link WebSiteType }
     * 
     */
    public WebSiteType createWebSiteType() {
        return new WebSiteType();
    }

    /**
     * Create an instance of {@link ImportConfigurationType }
     * 
     */
    public ImportConfigurationType createImportConfigurationType() {
        return new ImportConfigurationType();
    }

    /**
     * Create an instance of {@link AnalyzerElementType }
     * 
     */
    public AnalyzerElementType createAnalyzerElementType() {
        return new AnalyzerElementType();
    }

    /**
     * Create an instance of {@link VisibleTermFieldsType }
     * 
     */
    public VisibleTermFieldsType createVisibleTermFieldsType() {
        return new VisibleTermFieldsType();
    }

    /**
     * Create an instance of {@link LocalBusinessRuleType }
     * 
     */
    public LocalBusinessRuleType createLocalBusinessRuleType() {
        return new LocalBusinessRuleType();
    }

    /**
     * Create an instance of {@link VisibleTermFieldType }
     * 
     */
    public VisibleTermFieldType createVisibleTermFieldType() {
        return new VisibleTermFieldType();
    }

    /**
     * Create an instance of {@link EntityCrossReferenceType }
     * 
     */
    public EntityCrossReferenceType createEntityCrossReferenceType() {
        return new EntityCrossReferenceType();
    }

    /**
     * Create an instance of {@link MultiValueType }
     * 
     */
    public MultiValueType createMultiValueType() {
        return new MultiValueType();
    }

    /**
     * Create an instance of {@link KeysType }
     * 
     */
    public KeysType createKeysType() {
        return new KeysType();
    }

    /**
     * Create an instance of {@link AttributeGroupLinkType }
     * 
     */
    public AttributeGroupLinkType createAttributeGroupLinkType() {
        return new AttributeGroupLinkType();
    }

    /**
     * Create an instance of {@link STEPProductInformation }
     * 
     */
    public STEPProductInformation createSTEPProductInformation() {
        return new STEPProductInformation();
    }

    /**
     * Create an instance of {@link ContextListType }
     * 
     */
    public ContextListType createContextListType() {
        return new ContextListType();
    }

    /**
     * Create an instance of {@link ActionSetType }
     * 
     */
    public ActionSetType createActionSetType() {
        return new ActionSetType();
    }

    /**
     * Create an instance of {@link BasketType }
     * 
     */
    public BasketType createBasketType() {
        return new BasketType();
    }

    /**
     * Create an instance of {@link DeleteProductType }
     * 
     */
    public DeleteProductType createDeleteProductType() {
        return new DeleteProductType();
    }

    /**
     * Create an instance of {@link ProductCrossReferenceType }
     * 
     */
    public ProductCrossReferenceType createProductCrossReferenceType() {
        return new ProductCrossReferenceType();
    }

    /**
     * Create an instance of {@link ProductBasketLinkType }
     * 
     */
    public ProductBasketLinkType createProductBasketLinkType() {
        return new ProductBasketLinkType();
    }

    /**
     * Create an instance of {@link ECatalogsType }
     * 
     */
    public ECatalogsType createECatalogsType() {
        return new ECatalogsType();
    }

    /**
     * Create an instance of {@link AnalyzerItemType }
     * 
     */
    public AnalyzerItemType createAnalyzerItemType() {
        return new AnalyzerItemType();
    }

    /**
     * Create an instance of {@link ActionLinkType }
     * 
     */
    public ActionLinkType createActionLinkType() {
        return new ActionLinkType();
    }

    /**
     * Create an instance of {@link BusinessRulesType }
     * 
     */
    public BusinessRulesType createBusinessRulesType() {
        return new BusinessRulesType();
    }

    /**
     * Create an instance of {@link UnitLinkType }
     * 
     */
    public UnitLinkType createUnitLinkType() {
        return new UnitLinkType();
    }

    /**
     * Create an instance of {@link AssetPushLocationType }
     * 
     */
    public AssetPushLocationType createAssetPushLocationType() {
        return new AssetPushLocationType();
    }

    /**
     * Create an instance of {@link SuppressedEntityCrossReferenceType }
     * 
     */
    public SuppressedEntityCrossReferenceType createSuppressedEntityCrossReferenceType() {
        return new SuppressedEntityCrossReferenceType();
    }

    /**
     * Create an instance of {@link EntityElementType }
     * 
     */
    public EntityElementType createEntityElementType() {
        return new EntityElementType();
    }

    /**
     * Create an instance of {@link ActionSetListType }
     * 
     */
    public ActionSetListType createActionSetListType() {
        return new ActionSetListType();
    }

    /**
     * Create an instance of {@link AnalyzerPropType }
     * 
     */
    public AnalyzerPropType createAnalyzerPropType() {
        return new AnalyzerPropType();
    }

    /**
     * Create an instance of {@link CalculatedAttributeSettingsType }
     * 
     */
    public CalculatedAttributeSettingsType createCalculatedAttributeSettingsType() {
        return new CalculatedAttributeSettingsType();
    }

    /**
     * Create an instance of {@link CollectionListType }
     * 
     */
    public CollectionListType createCollectionListType() {
        return new CollectionListType();
    }

    /**
     * Create an instance of {@link TagType }
     * 
     */
    public TagType createTagType() {
        return new TagType();
    }

    /**
     * Create an instance of {@link ProductType }
     * 
     */
    public ProductType createProductType() {
        return new ProductType();
    }

    /**
     * Create an instance of {@link UnitTemplateType }
     * 
     */
    public UnitTemplateType createUnitTemplateType() {
        return new UnitTemplateType();
    }

    /**
     * Create an instance of {@link DeleteAttributeLinkType }
     * 
     */
    public DeleteAttributeLinkType createDeleteAttributeLinkType() {
        return new DeleteAttributeLinkType();
    }

    /**
     * Create an instance of {@link ImportConfigurationsType }
     * 
     */
    public ImportConfigurationsType createImportConfigurationsType() {
        return new ImportConfigurationsType();
    }

    /**
     * Create an instance of {@link MetaDataType }
     * 
     */
    public MetaDataType createMetaDataType() {
        return new MetaDataType();
    }

    /**
     * Create an instance of {@link UserGroupListType }
     * 
     */
    public UserGroupListType createUserGroupListType() {
        return new UserGroupListType();
    }

    /**
     * Create an instance of {@link PlannedPageType }
     * 
     */
    public PlannedPageType createPlannedPageType() {
        return new PlannedPageType();
    }

    /**
     * Create an instance of {@link ValueTemplateType }
     * 
     */
    public ValueTemplateType createValueTemplateType() {
        return new ValueTemplateType();
    }

    /**
     * Create an instance of {@link TransformationLookupTableConfigurationsType }
     * 
     */
    public TransformationLookupTableConfigurationsType createTransformationLookupTableConfigurationsType() {
        return new TransformationLookupTableConfigurationsType();
    }

    /**
     * Create an instance of {@link PageTemplateLinkType }
     * 
     */
    public PageTemplateLinkType createPageTemplateLinkType() {
        return new PageTemplateLinkType();
    }

    /**
     * Create an instance of {@link AssetElementType }
     * 
     */
    public AssetElementType createAssetElementType() {
        return new AssetElementType();
    }

    /**
     * Create an instance of {@link PagesType }
     * 
     */
    public PagesType createPagesType() {
        return new PagesType();
    }

    /**
     * Create an instance of {@link ValueFilterType }
     * 
     */
    public ValueFilterType createValueFilterType() {
        return new ValueFilterType();
    }

    /**
     * Create an instance of {@link AssetCrossReferenceTypeType }
     * 
     */
    public AssetCrossReferenceTypeType createAssetCrossReferenceTypeType() {
        return new AssetCrossReferenceTypeType();
    }

    /**
     * Create an instance of {@link TableTypesType }
     * 
     */
    public TableTypesType createTableTypesType() {
        return new TableTypesType();
    }

    /**
     * Create an instance of {@link ProductsType }
     * 
     */
    public ProductsType createProductsType() {
        return new ProductsType();
    }

    /**
     * Create an instance of {@link CollectionGroupType }
     * 
     */
    public CollectionGroupType createCollectionGroupType() {
        return new CollectionGroupType();
    }

    /**
     * Create an instance of {@link DeleteProductsType }
     * 
     */
    public DeleteProductsType createDeleteProductsType() {
        return new DeleteProductsType();
    }

    /**
     * Create an instance of {@link SuppressedProductCrossReferenceType }
     * 
     */
    public SuppressedProductCrossReferenceType createSuppressedProductCrossReferenceType() {
        return new SuppressedProductCrossReferenceType();
    }

    /**
     * Create an instance of {@link ContextCrossReferenceType }
     * 
     */
    public ContextCrossReferenceType createContextCrossReferenceType() {
        return new ContextCrossReferenceType();
    }

    /**
     * Create an instance of {@link DeleteAssetType }
     * 
     */
    public DeleteAssetType createDeleteAssetType() {
        return new DeleteAssetType();
    }

    /**
     * Create an instance of {@link ProductElementType }
     * 
     */
    public ProductElementType createProductElementType() {
        return new ProductElementType();
    }

    /**
     * Create an instance of {@link EntityCrossReferenceTypeType }
     * 
     */
    public EntityCrossReferenceTypeType createEntityCrossReferenceTypeType() {
        return new EntityCrossReferenceTypeType();
    }

    /**
     * Create an instance of {@link DeleteEntitiesType }
     * 
     */
    public DeleteEntitiesType createDeleteEntitiesType() {
        return new DeleteEntitiesType();
    }

    /**
     * Create an instance of {@link ClassificationTemplateType }
     * 
     */
    public ClassificationTemplateType createClassificationTemplateType() {
        return new ClassificationTemplateType();
    }

    /**
     * Create an instance of {@link ColumnType }
     * 
     */
    public ColumnType createColumnType() {
        return new ColumnType();
    }

    /**
     * Create an instance of {@link DimensionLinkType }
     * 
     */
    public DimensionLinkType createDimensionLinkType() {
        return new DimensionLinkType();
    }

    /**
     * Create an instance of {@link ListOfValuesGroupType }
     * 
     */
    public ListOfValuesGroupType createListOfValuesGroupType() {
        return new ListOfValuesGroupType();
    }

    /**
     * Create an instance of {@link DataPoolPublisherType }
     * 
     */
    public DataPoolPublisherType createDataPoolPublisherType() {
        return new DataPoolPublisherType();
    }

    /**
     * Create an instance of {@link SuppressedClassificationCrossReferenceType }
     * 
     */
    public SuppressedClassificationCrossReferenceType createSuppressedClassificationCrossReferenceType() {
        return new SuppressedClassificationCrossReferenceType();
    }

    /**
     * Create an instance of {@link AttributeGroupListType }
     * 
     */
    public AttributeGroupListType createAttributeGroupListType() {
        return new AttributeGroupListType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link AssetSettingsType }
     * 
     */
    public AssetSettingsType createAssetSettingsType() {
        return new AssetSettingsType();
    }

    /**
     * Create an instance of {@link CollectionType }
     * 
     */
    public CollectionType createCollectionType() {
        return new CollectionType();
    }

    /**
     * Create an instance of {@link TagListType }
     * 
     */
    public TagListType createTagListType() {
        return new TagListType();
    }

    /**
     * Create an instance of {@link AttributeTransformationGroupType }
     * 
     */
    public AttributeTransformationGroupType createAttributeTransformationGroupType() {
        return new AttributeTransformationGroupType();
    }

    /**
     * Create an instance of {@link KeyType }
     * 
     */
    public KeyType createKeyType() {
        return new KeyType();
    }

    /**
     * Create an instance of {@link MIMETypeType }
     * 
     */
    public MIMETypeType createMIMETypeType() {
        return new MIMETypeType();
    }

    /**
     * Create an instance of {@link ValueType }
     * 
     */
    public ValueType createValueType() {
        return new ValueType();
    }

    /**
     * Create an instance of {@link PickupLayoutType }
     * 
     */
    public PickupLayoutType createPickupLayoutType() {
        return new PickupLayoutType();
    }

    /**
     * Create an instance of {@link DataPoolReceiverType }
     * 
     */
    public DataPoolReceiverType createDataPoolReceiverType() {
        return new DataPoolReceiverType();
    }

    /**
     * Create an instance of {@link ClassificationProductLinkTypeType }
     * 
     */
    public ClassificationProductLinkTypeType createClassificationProductLinkTypeType() {
        return new ClassificationProductLinkTypeType();
    }

    /**
     * Create an instance of {@link UserTypesType }
     * 
     */
    public UserTypesType createUserTypesType() {
        return new UserTypesType();
    }

    /**
     * Create an instance of {@link ProductReferenceType }
     * 
     */
    public ProductReferenceType createProductReferenceType() {
        return new ProductReferenceType();
    }

    /**
     * Create an instance of {@link TableType }
     * 
     */
    public TableType createTableType() {
        return new TableType();
    }

    /**
     * Create an instance of {@link PortalConfigurationType }
     * 
     */
    public PortalConfigurationType createPortalConfigurationType() {
        return new PortalConfigurationType();
    }

    /**
     * Create an instance of {@link CurrentTasksType }
     * 
     */
    public CurrentTasksType createCurrentTasksType() {
        return new CurrentTasksType();
    }

    /**
     * Create an instance of {@link VersionType }
     * 
     */
    public VersionType createVersionType() {
        return new VersionType();
    }

    /**
     * Create an instance of {@link ReplaceCrossReferenceType }
     * 
     */
    public ReplaceCrossReferenceType createReplaceCrossReferenceType() {
        return new ReplaceCrossReferenceType();
    }

    /**
     * Create an instance of {@link AssetsType }
     * 
     */
    public AssetsType createAssetsType() {
        return new AssetsType();
    }

    /**
     * Create an instance of {@link WorkspaceCrossReferenceType }
     * 
     */
    public WorkspaceCrossReferenceType createWorkspaceCrossReferenceType() {
        return new WorkspaceCrossReferenceType();
    }

    /**
     * Create an instance of {@link AttributeGroupType }
     * 
     */
    public AttributeGroupType createAttributeGroupType() {
        return new AttributeGroupType();
    }

    /**
     * Create an instance of {@link DeleteClassificationReferenceType }
     * 
     */
    public DeleteClassificationReferenceType createDeleteClassificationReferenceType() {
        return new DeleteClassificationReferenceType();
    }

    /**
     * Create an instance of {@link UnitType }
     * 
     */
    public UnitType createUnitType() {
        return new UnitType();
    }

    /**
     * Create an instance of {@link CharacterTagGroupType }
     * 
     */
    public CharacterTagGroupType createCharacterTagGroupType() {
        return new CharacterTagGroupType();
    }

    /**
     * Create an instance of {@link TemplateLayoutType }
     * 
     */
    public TemplateLayoutType createTemplateLayoutType() {
        return new TemplateLayoutType();
    }

    /**
     * Create an instance of {@link SetupGroupLinkType }
     * 
     */
    public SetupGroupLinkType createSetupGroupLinkType() {
        return new SetupGroupLinkType();
    }

    /**
     * Create an instance of {@link DataPoolSubscriptionType }
     * 
     */
    public DataPoolSubscriptionType createDataPoolSubscriptionType() {
        return new DataPoolSubscriptionType();
    }

    /**
     * Create an instance of {@link SuppressedWorkspaceCrossReferenceType }
     * 
     */
    public SuppressedWorkspaceCrossReferenceType createSuppressedWorkspaceCrossReferenceType() {
        return new SuppressedWorkspaceCrossReferenceType();
    }

    /**
     * Create an instance of {@link AttributeListType }
     * 
     */
    public AttributeListType createAttributeListType() {
        return new AttributeListType();
    }

    /**
     * Create an instance of {@link CharacterTagType }
     * 
     */
    public CharacterTagType createCharacterTagType() {
        return new CharacterTagType();
    }

    /**
     * Create an instance of {@link StyleTagGroupType }
     * 
     */
    public StyleTagGroupType createStyleTagGroupType() {
        return new StyleTagGroupType();
    }

    /**
     * Create an instance of {@link AttributeLinkType }
     * 
     */
    public AttributeLinkType createAttributeLinkType() {
        return new AttributeLinkType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link BusinessRuleType }
     * 
     */
    public BusinessRuleType createBusinessRuleType() {
        return new BusinessRuleType();
    }

    /**
     * Create an instance of {@link ValuesType }
     * 
     */
    public ValuesType createValuesType() {
        return new ValuesType();
    }

    /**
     * Create an instance of {@link NoteElementType }
     * 
     */
    public NoteElementType createNoteElementType() {
        return new NoteElementType();
    }

    /**
     * Create an instance of {@link RowTypeType }
     * 
     */
    public RowTypeType createRowTypeType() {
        return new RowTypeType();
    }

    /**
     * Create an instance of {@link GUISetupType }
     * 
     */
    public GUISetupType createGUISetupType() {
        return new GUISetupType();
    }

    /**
     * Create an instance of {@link PageType }
     * 
     */
    public PageType createPageType() {
        return new PageType();
    }

    /**
     * Create an instance of {@link ClassificationCrossReferenceTypeType }
     * 
     */
    public ClassificationCrossReferenceTypeType createClassificationCrossReferenceTypeType() {
        return new ClassificationCrossReferenceTypeType();
    }

    /**
     * Create an instance of {@link DeleteAssetCrossReferenceType }
     * 
     */
    public DeleteAssetCrossReferenceType createDeleteAssetCrossReferenceType() {
        return new DeleteAssetCrossReferenceType();
    }

    /**
     * Create an instance of {@link DeleteClassificationsType }
     * 
     */
    public DeleteClassificationsType createDeleteClassificationsType() {
        return new DeleteClassificationsType();
    }

    /**
     * Create an instance of {@link AttributeTemplateType }
     * 
     */
    public AttributeTemplateType createAttributeTemplateType() {
        return new AttributeTemplateType();
    }

    /**
     * Create an instance of {@link NoteRecordType }
     * 
     */
    public NoteRecordType createNoteRecordType() {
        return new NoteRecordType();
    }

    /**
     * Create an instance of {@link WorkspaceCrossReferenceTypeType }
     * 
     */
    public WorkspaceCrossReferenceTypeType createWorkspaceCrossReferenceTypeType() {
        return new WorkspaceCrossReferenceTypeType();
    }

    /**
     * Create an instance of {@link InBoundIntegrationEndpointType }
     * 
     */
    public InBoundIntegrationEndpointType createInBoundIntegrationEndpointType() {
        return new InBoundIntegrationEndpointType();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link UnitOutputTemplateType }
     * 
     */
    public UnitOutputTemplateType createUnitOutputTemplateType() {
        return new UnitOutputTemplateType();
    }

    /**
     * Create an instance of {@link GlobalSettingsType }
     * 
     */
    public GlobalSettingsType createGlobalSettingsType() {
        return new GlobalSettingsType();
    }

    /**
     * Create an instance of {@link TermsType }
     * 
     */
    public TermsType createTermsType() {
        return new TermsType();
    }

    /**
     * Create an instance of {@link DataPoolRecipientType }
     * 
     */
    public DataPoolRecipientType createDataPoolRecipientType() {
        return new DataPoolRecipientType();
    }

    /**
     * Create an instance of {@link ReplaceProductToAssetCrossReferenceType }
     * 
     */
    public ReplaceProductToAssetCrossReferenceType createReplaceProductToAssetCrossReferenceType() {
        return new ReplaceProductToAssetCrossReferenceType();
    }

    /**
     * Create an instance of {@link PublicationSectionType }
     * 
     */
    public PublicationSectionType createPublicationSectionType() {
        return new PublicationSectionType();
    }

    /**
     * Create an instance of {@link SpecialCharacterTagGroupType }
     * 
     */
    public SpecialCharacterTagGroupType createSpecialCharacterTagGroupType() {
        return new SpecialCharacterTagGroupType();
    }

    /**
     * Create an instance of {@link ProductTemplateLinkType }
     * 
     */
    public ProductTemplateLinkType createProductTemplateLinkType() {
        return new ProductTemplateLinkType();
    }

    /**
     * Create an instance of {@link TagGroupListType }
     * 
     */
    public TagGroupListType createTagGroupListType() {
        return new TagGroupListType();
    }

    /**
     * Create an instance of {@link BusinessRuleLinkType }
     * 
     */
    public BusinessRuleLinkType createBusinessRuleLinkType() {
        return new BusinessRuleLinkType();
    }

    /**
     * Create an instance of {@link PortalConfigurationsType }
     * 
     */
    public PortalConfigurationsType createPortalConfigurationsType() {
        return new PortalConfigurationsType();
    }

    /**
     * Create an instance of {@link ProductCrossReferenceTypeType }
     * 
     */
    public ProductCrossReferenceTypeType createProductCrossReferenceTypeType() {
        return new ProductCrossReferenceTypeType();
    }

    /**
     * Create an instance of {@link ProductMarkerElementType }
     * 
     */
    public ProductMarkerElementType createProductMarkerElementType() {
        return new ProductMarkerElementType();
    }

    /**
     * Create an instance of {@link CellType }
     * 
     */
    public CellType createCellType() {
        return new CellType();
    }

    /**
     * Create an instance of {@link FootnoteTagGroupType }
     * 
     */
    public FootnoteTagGroupType createFootnoteTagGroupType() {
        return new FootnoteTagGroupType();
    }

    /**
     * Create an instance of {@link HyperlinkTagType }
     * 
     */
    public HyperlinkTagType createHyperlinkTagType() {
        return new HyperlinkTagType();
    }

    /**
     * Create an instance of {@link QualifierType }
     * 
     */
    public QualifierType createQualifierType() {
        return new QualifierType();
    }

    /**
     * Create an instance of {@link PublicationGroupsType }
     * 
     */
    public PublicationGroupsType createPublicationGroupsType() {
        return new PublicationGroupsType();
    }

    /**
     * Create an instance of {@link CrossReferenceTypesType }
     * 
     */
    public CrossReferenceTypesType createCrossReferenceTypesType() {
        return new CrossReferenceTypesType();
    }

    /**
     * Create an instance of {@link SuppressedAssetCrossReferenceType }
     * 
     */
    public SuppressedAssetCrossReferenceType createSuppressedAssetCrossReferenceType() {
        return new SuppressedAssetCrossReferenceType();
    }

    /**
     * Create an instance of {@link PickupPageType }
     * 
     */
    public PickupPageType createPickupPageType() {
        return new PickupPageType();
    }

    /**
     * Create an instance of {@link SequenceProductType }
     * 
     */
    public SequenceProductType createSequenceProductType() {
        return new SequenceProductType();
    }

    /**
     * Create an instance of {@link AssetMarkerElementType }
     * 
     */
    public AssetMarkerElementType createAssetMarkerElementType() {
        return new AssetMarkerElementType();
    }

    /**
     * Create an instance of {@link ClassificationBasketLinkType }
     * 
     */
    public ClassificationBasketLinkType createClassificationBasketLinkType() {
        return new ClassificationBasketLinkType();
    }

    /**
     * Create an instance of {@link BulkUpdateConfigurationsType }
     * 
     */
    public BulkUpdateConfigurationsType createBulkUpdateConfigurationsType() {
        return new BulkUpdateConfigurationsType();
    }

    /**
     * Create an instance of {@link UnitFamilyType }
     * 
     */
    public UnitFamilyType createUnitFamilyType() {
        return new UnitFamilyType();
    }

    /**
     * Create an instance of {@link ColumnTypeType }
     * 
     */
    public ColumnTypeType createColumnTypeType() {
        return new ColumnTypeType();
    }

    /**
     * Create an instance of {@link AnalyzerListsType }
     * 
     */
    public AnalyzerListsType createAnalyzerListsType() {
        return new AnalyzerListsType();
    }

    /**
     * Create an instance of {@link WebSitesType }
     * 
     */
    public WebSitesType createWebSitesType() {
        return new WebSitesType();
    }

    /**
     * Create an instance of {@link UnitListType }
     * 
     */
    public UnitListType createUnitListType() {
        return new UnitListType();
    }

    /**
     * Create an instance of {@link QualifiersType }
     * 
     */
    public QualifiersType createQualifiersType() {
        return new QualifiersType();
    }

    /**
     * Create an instance of {@link TableTypeLinkType }
     * 
     */
    public TableTypeLinkType createTableTypeLinkType() {
        return new TableTypeLinkType();
    }

    /**
     * Create an instance of {@link ColumnTypesType }
     * 
     */
    public ColumnTypesType createColumnTypesType() {
        return new ColumnTypesType();
    }

    /**
     * Create an instance of {@link AttributeTransformationGroupsType }
     * 
     */
    public AttributeTransformationGroupsType createAttributeTransformationGroupsType() {
        return new AttributeTransformationGroupsType();
    }

    /**
     * Create an instance of {@link AnalyzerListType }
     * 
     */
    public AnalyzerListType createAnalyzerListType() {
        return new AnalyzerListType();
    }

    /**
     * Create an instance of {@link ClassificationElementType }
     * 
     */
    public ClassificationElementType createClassificationElementType() {
        return new ClassificationElementType();
    }

    /**
     * Create an instance of {@link PageContentsType }
     * 
     */
    public PageContentsType createPageContentsType() {
        return new PageContentsType();
    }

    /**
     * Create an instance of {@link AssetType }
     * 
     */
    public AssetType createAssetType() {
        return new AssetType();
    }

    /**
     * Create an instance of {@link AssetCrossReferenceType }
     * 
     */
    public AssetCrossReferenceType createAssetCrossReferenceType() {
        return new AssetCrossReferenceType();
    }

    /**
     * Create an instance of {@link TextElementType }
     * 
     */
    public TextElementType createTextElementType() {
        return new TextElementType();
    }

    /**
     * Create an instance of {@link EventQueuesType }
     * 
     */
    public EventQueuesType createEventQueuesType() {
        return new EventQueuesType();
    }

    /**
     * Create an instance of {@link VersionLinkType }
     * 
     */
    public VersionLinkType createVersionLinkType() {
        return new VersionLinkType();
    }

    /**
     * Create an instance of {@link ClassificationReferenceType }
     * 
     */
    public ClassificationReferenceType createClassificationReferenceType() {
        return new ClassificationReferenceType();
    }

    /**
     * Create an instance of {@link StyleTagType }
     * 
     */
    public StyleTagType createStyleTagType() {
        return new StyleTagType();
    }

    /**
     * Create an instance of {@link ContextCrossReferenceTypeType }
     * 
     */
    public ContextCrossReferenceTypeType createContextCrossReferenceTypeType() {
        return new ContextCrossReferenceTypeType();
    }

    /**
     * Create an instance of {@link FootnoteTagType }
     * 
     */
    public FootnoteTagType createFootnoteTagType() {
        return new FootnoteTagType();
    }

    /**
     * Create an instance of {@link ListOfValueLinkType }
     * 
     */
    public ListOfValueLinkType createListOfValueLinkType() {
        return new ListOfValueLinkType();
    }

    /**
     * Create an instance of {@link UserGroupLinkType }
     * 
     */
    public UserGroupLinkType createUserGroupLinkType() {
        return new UserGroupLinkType();
    }

    /**
     * Create an instance of {@link TargetUserTypeLinkType }
     * 
     */
    public TargetUserTypeLinkType createTargetUserTypeLinkType() {
        return new TargetUserTypeLinkType();
    }

    /**
     * Create an instance of {@link PublicationGroupType }
     * 
     */
    public PublicationGroupType createPublicationGroupType() {
        return new PublicationGroupType();
    }

    /**
     * Create an instance of {@link ListsOfValuesType }
     * 
     */
    public ListsOfValuesType createListsOfValuesType() {
        return new ListsOfValuesType();
    }

    /**
     * Create an instance of {@link SetupGroupType }
     * 
     */
    public SetupGroupType createSetupGroupType() {
        return new SetupGroupType();
    }

    /**
     * Create an instance of {@link AnalyzerResultType }
     * 
     */
    public AnalyzerResultType createAnalyzerResultType() {
        return new AnalyzerResultType();
    }

    /**
     * Create an instance of {@link AnalyzerItemsType }
     * 
     */
    public AnalyzerItemsType createAnalyzerItemsType() {
        return new AnalyzerItemsType();
    }

    /**
     * Create an instance of {@link DeleteEntityType }
     * 
     */
    public DeleteEntityType createDeleteEntityType() {
        return new DeleteEntityType();
    }

    /**
     * Create an instance of {@link EdgeTypeType }
     * 
     */
    public EdgeTypeType createEdgeTypeType() {
        return new EdgeTypeType();
    }

    /**
     * Create an instance of {@link EdgeTypesType }
     * 
     */
    public EdgeTypesType createEdgeTypesType() {
        return new EdgeTypesType();
    }

    /**
     * Create an instance of {@link OnApproveType }
     * 
     */
    public OnApproveType createOnApproveType() {
        return new OnApproveType();
    }

    /**
     * Create an instance of {@link DataPoolsType }
     * 
     */
    public DataPoolsType createDataPoolsType() {
        return new DataPoolsType();
    }

    /**
     * Create an instance of {@link ExportConfigurationsType }
     * 
     */
    public ExportConfigurationsType createExportConfigurationsType() {
        return new ExportConfigurationsType();
    }

    /**
     * Create an instance of {@link STEPWorkflowType }
     * 
     */
    public STEPWorkflowType createSTEPWorkflowType() {
        return new STEPWorkflowType();
    }

    /**
     * Create an instance of {@link ValidationType }
     * 
     */
    public ValidationType createValidationType() {
        return new ValidationType();
    }

    /**
     * Create an instance of {@link AssetTemplateType }
     * 
     */
    public AssetTemplateType createAssetTemplateType() {
        return new AssetTemplateType();
    }

    /**
     * Create an instance of {@link ReplaceClassificationReferenceType }
     * 
     */
    public ReplaceClassificationReferenceType createReplaceClassificationReferenceType() {
        return new ReplaceClassificationReferenceType();
    }

    /**
     * Create an instance of {@link RowType }
     * 
     */
    public RowType createRowType() {
        return new RowType();
    }

    /**
     * Create an instance of {@link SpecialCharacterTagType }
     * 
     */
    public SpecialCharacterTagType createSpecialCharacterTagType() {
        return new SpecialCharacterTagType();
    }

    /**
     * Create an instance of {@link PackagingReferenceType }
     * 
     */
    public PackagingReferenceType createPackagingReferenceType() {
        return new PackagingReferenceType();
    }

    /**
     * Create an instance of {@link DimensionType }
     * 
     */
    public DimensionType createDimensionType() {
        return new DimensionType();
    }

    /**
     * Create an instance of {@link UserGroupType }
     * 
     */
    public UserGroupType createUserGroupType() {
        return new UserGroupType();
    }

    /**
     * Create an instance of {@link ListOfValueType }
     * 
     */
    public ListOfValueType createListOfValueType() {
        return new ListOfValueType();
    }

    /**
     * Create an instance of {@link ClassificationCrossReferenceType }
     * 
     */
    public ClassificationCrossReferenceType createClassificationCrossReferenceType() {
        return new ClassificationCrossReferenceType();
    }

    /**
     * Create an instance of {@link PrivilegeRuleType }
     * 
     */
    public PrivilegeRuleType createPrivilegeRuleType() {
        return new PrivilegeRuleType();
    }

    /**
     * Create an instance of {@link DimensionPointType }
     * 
     */
    public DimensionPointType createDimensionPointType() {
        return new DimensionPointType();
    }

    /**
     * Create an instance of {@link EntityType }
     * 
     */
    public EntityType createEntityType() {
        return new EntityType();
    }

    /**
     * Create an instance of {@link PublicationType }
     * 
     */
    public PublicationType createPublicationType() {
        return new PublicationType();
    }

    /**
     * Create an instance of {@link SuppressedClassificationReferenceType }
     * 
     */
    public SuppressedClassificationReferenceType createSuppressedClassificationReferenceType() {
        return new SuppressedClassificationReferenceType();
    }

    /**
     * Create an instance of {@link LinkTypeType }
     * 
     */
    public LinkTypeType createLinkTypeType() {
        return new LinkTypeType();
    }

    /**
     * Create an instance of {@link DeleteClassificationCrossReferenceType }
     * 
     */
    public DeleteClassificationCrossReferenceType createDeleteClassificationCrossReferenceType() {
        return new DeleteClassificationCrossReferenceType();
    }

    /**
     * Create an instance of {@link FormattingType }
     * 
     */
    public FormattingType createFormattingType() {
        return new FormattingType();
    }

    /**
     * Create an instance of {@link KeyFormulaType }
     * 
     */
    public KeyFormulaType createKeyFormulaType() {
        return new KeyFormulaType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GUISetupAdvanced", scope = GUISetupType.class)
    public JAXBElement<String> createGUISetupTypeGUISetupAdvanced(String value) {
        return new JAXBElement<String>(_GUISetupTypeGUISetupAdvanced_QNAME, String.class, GUISetupType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GUISetupDisabled", scope = GUISetupType.class)
    public JAXBElement<String> createGUISetupTypeGUISetupDisabled(String value) {
        return new JAXBElement<String>(_GUISetupTypeGUISetupDisabled_QNAME, String.class, GUISetupType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GUISetupEnabled", scope = GUISetupType.class)
    public JAXBElement<String> createGUISetupTypeGUISetupEnabled(String value) {
        return new JAXBElement<String>(_GUISetupTypeGUISetupEnabled_QNAME, String.class, GUISetupType.class, value);
    }

}
