//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.13 at 03:27:41 PM IST 
//


package com.kraft.pim.step;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PageContentsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PageContentsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;element name="NoteElement" type="{}NoteElementType"/>
 *         &lt;element name="ProductMarkerElement" type="{}ProductMarkerElementType"/>
 *         &lt;element name="AssetMarkerElement" type="{}AssetMarkerElementType"/>
 *         &lt;element name="ProductElement" type="{}ProductElementType"/>
 *         &lt;element name="AssetElement" type="{}AssetElementType"/>
 *         &lt;element name="TextElement" type="{}TextElementType"/>
 *         &lt;element name="ClassificationElement" type="{}ClassificationElementType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PageContentsType", propOrder = {
    "noteElement",
    "productMarkerElement",
    "assetMarkerElement",
    "productElement",
    "assetElement",
    "textElement",
    "classificationElement"
})
public class PageContentsType {

    @XmlElement(name = "NoteElement")
    protected NoteElementType noteElement;
    @XmlElement(name = "ProductMarkerElement")
    protected ProductMarkerElementType productMarkerElement;
    @XmlElement(name = "AssetMarkerElement")
    protected AssetMarkerElementType assetMarkerElement;
    @XmlElement(name = "ProductElement")
    protected ProductElementType productElement;
    @XmlElement(name = "AssetElement")
    protected AssetElementType assetElement;
    @XmlElement(name = "TextElement")
    protected TextElementType textElement;
    @XmlElement(name = "ClassificationElement")
    protected ClassificationElementType classificationElement;

    /**
     * Gets the value of the noteElement property.
     * 
     * @return
     *     possible object is
     *     {@link NoteElementType }
     *     
     */
    public NoteElementType getNoteElement() {
        return noteElement;
    }

    /**
     * Sets the value of the noteElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoteElementType }
     *     
     */
    public void setNoteElement(NoteElementType value) {
        this.noteElement = value;
    }

    /**
     * Gets the value of the productMarkerElement property.
     * 
     * @return
     *     possible object is
     *     {@link ProductMarkerElementType }
     *     
     */
    public ProductMarkerElementType getProductMarkerElement() {
        return productMarkerElement;
    }

    /**
     * Sets the value of the productMarkerElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductMarkerElementType }
     *     
     */
    public void setProductMarkerElement(ProductMarkerElementType value) {
        this.productMarkerElement = value;
    }

    /**
     * Gets the value of the assetMarkerElement property.
     * 
     * @return
     *     possible object is
     *     {@link AssetMarkerElementType }
     *     
     */
    public AssetMarkerElementType getAssetMarkerElement() {
        return assetMarkerElement;
    }

    /**
     * Sets the value of the assetMarkerElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetMarkerElementType }
     *     
     */
    public void setAssetMarkerElement(AssetMarkerElementType value) {
        this.assetMarkerElement = value;
    }

    /**
     * Gets the value of the productElement property.
     * 
     * @return
     *     possible object is
     *     {@link ProductElementType }
     *     
     */
    public ProductElementType getProductElement() {
        return productElement;
    }

    /**
     * Sets the value of the productElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductElementType }
     *     
     */
    public void setProductElement(ProductElementType value) {
        this.productElement = value;
    }

    /**
     * Gets the value of the assetElement property.
     * 
     * @return
     *     possible object is
     *     {@link AssetElementType }
     *     
     */
    public AssetElementType getAssetElement() {
        return assetElement;
    }

    /**
     * Sets the value of the assetElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetElementType }
     *     
     */
    public void setAssetElement(AssetElementType value) {
        this.assetElement = value;
    }

    /**
     * Gets the value of the textElement property.
     * 
     * @return
     *     possible object is
     *     {@link TextElementType }
     *     
     */
    public TextElementType getTextElement() {
        return textElement;
    }

    /**
     * Sets the value of the textElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextElementType }
     *     
     */
    public void setTextElement(TextElementType value) {
        this.textElement = value;
    }

    /**
     * Gets the value of the classificationElement property.
     * 
     * @return
     *     possible object is
     *     {@link ClassificationElementType }
     *     
     */
    public ClassificationElementType getClassificationElement() {
        return classificationElement;
    }

    /**
     * Sets the value of the classificationElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassificationElementType }
     *     
     */
    public void setClassificationElement(ClassificationElementType value) {
        this.classificationElement = value;
    }

}
