//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.13 at 03:27:41 PM IST 
//


package com.kraft.pim.step;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 A configuration of a STEP Workflow.
 *             
 * 
 * <p>Java class for STEPWorkflowType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STEPWorkflowType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BusinessRuleLink" type="{}BusinessRuleLinkType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SetupGroupLink" type="{}SetupGroupLinkType" minOccurs="0"/>
 *         &lt;element name="Name" type="{}NameType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MetaData" type="{}MetaDataType" minOccurs="0"/>
 *         &lt;element name="ValidUserTypeLink" type="{}UserTypeLinkType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Configuration" type="{}ConfigurationType" minOccurs="0"/>
 *         &lt;element name="LocalBusinessRule" type="{}LocalBusinessRuleType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{}StepID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STEPWorkflowType", propOrder = {
    "businessRuleLink",
    "setupGroupLink",
    "name",
    "metaData",
    "validUserTypeLink",
    "configuration",
    "localBusinessRule"
})
public class STEPWorkflowType {

    @XmlElement(name = "BusinessRuleLink")
    protected List<BusinessRuleLinkType> businessRuleLink;
    @XmlElement(name = "SetupGroupLink")
    protected SetupGroupLinkType setupGroupLink;
    @XmlElement(name = "Name")
    protected List<NameType> name;
    @XmlElement(name = "MetaData")
    protected MetaDataType metaData;
    @XmlElement(name = "ValidUserTypeLink")
    protected List<UserTypeLinkType> validUserTypeLink;
    @XmlElement(name = "Configuration")
    protected byte[] configuration;
    @XmlElement(name = "LocalBusinessRule")
    protected List<LocalBusinessRuleType> localBusinessRule;
    @XmlAttribute(name = "ID", required = true)
    protected String id;

    /**
     * Gets the value of the businessRuleLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the businessRuleLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBusinessRuleLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BusinessRuleLinkType }
     * 
     * 
     */
    public List<BusinessRuleLinkType> getBusinessRuleLink() {
        if (businessRuleLink == null) {
            businessRuleLink = new ArrayList<BusinessRuleLinkType>();
        }
        return this.businessRuleLink;
    }

    /**
     * Gets the value of the setupGroupLink property.
     * 
     * @return
     *     possible object is
     *     {@link SetupGroupLinkType }
     *     
     */
    public SetupGroupLinkType getSetupGroupLink() {
        return setupGroupLink;
    }

    /**
     * Sets the value of the setupGroupLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetupGroupLinkType }
     *     
     */
    public void setSetupGroupLink(SetupGroupLinkType value) {
        this.setupGroupLink = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameType }
     * 
     * 
     */
    public List<NameType> getName() {
        if (name == null) {
            name = new ArrayList<NameType>();
        }
        return this.name;
    }

    /**
     * Gets the value of the metaData property.
     * 
     * @return
     *     possible object is
     *     {@link MetaDataType }
     *     
     */
    public MetaDataType getMetaData() {
        return metaData;
    }

    /**
     * Sets the value of the metaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaDataType }
     *     
     */
    public void setMetaData(MetaDataType value) {
        this.metaData = value;
    }

    /**
     * Gets the value of the validUserTypeLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validUserTypeLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidUserTypeLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserTypeLinkType }
     * 
     * 
     */
    public List<UserTypeLinkType> getValidUserTypeLink() {
        if (validUserTypeLink == null) {
            validUserTypeLink = new ArrayList<UserTypeLinkType>();
        }
        return this.validUserTypeLink;
    }

    /**
     * Gets the value of the configuration property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setConfiguration(byte[] value) {
        this.configuration = ((byte[]) value);
    }

    /**
     * Gets the value of the localBusinessRule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the localBusinessRule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocalBusinessRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocalBusinessRuleType }
     * 
     * 
     */
    public List<LocalBusinessRuleType> getLocalBusinessRule() {
        if (localBusinessRule == null) {
            localBusinessRule = new ArrayList<LocalBusinessRuleType>();
        }
        return this.localBusinessRule;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
