//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.13 at 03:27:41 PM IST 
//


package com.kraft.pim.step;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The list of all tag groups.
 *             
 * 
 * <p>Java class for TagGroupListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TagGroupListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StyleTagGroup" type="{}StyleTagGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SpecialCharacterTagGroup" type="{}SpecialCharacterTagGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CharacterTagGroup" type="{}CharacterTagGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FootnoteTagGroup" type="{}FootnoteTagGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="HyperlinkTagGroup" type="{}HyperlinkTagGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TagGroupListType", propOrder = {
    "styleTagGroup",
    "specialCharacterTagGroup",
    "characterTagGroup",
    "footnoteTagGroup",
    "hyperlinkTagGroup"
})
public class TagGroupListType {

    @XmlElement(name = "StyleTagGroup")
    protected List<StyleTagGroupType> styleTagGroup;
    @XmlElement(name = "SpecialCharacterTagGroup")
    protected List<SpecialCharacterTagGroupType> specialCharacterTagGroup;
    @XmlElement(name = "CharacterTagGroup")
    protected List<CharacterTagGroupType> characterTagGroup;
    @XmlElement(name = "FootnoteTagGroup")
    protected List<FootnoteTagGroupType> footnoteTagGroup;
    @XmlElement(name = "HyperlinkTagGroup")
    protected List<HyperlinkTagGroupType> hyperlinkTagGroup;

    /**
     * Gets the value of the styleTagGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the styleTagGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStyleTagGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StyleTagGroupType }
     * 
     * 
     */
    public List<StyleTagGroupType> getStyleTagGroup() {
        if (styleTagGroup == null) {
            styleTagGroup = new ArrayList<StyleTagGroupType>();
        }
        return this.styleTagGroup;
    }

    /**
     * Gets the value of the specialCharacterTagGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specialCharacterTagGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecialCharacterTagGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpecialCharacterTagGroupType }
     * 
     * 
     */
    public List<SpecialCharacterTagGroupType> getSpecialCharacterTagGroup() {
        if (specialCharacterTagGroup == null) {
            specialCharacterTagGroup = new ArrayList<SpecialCharacterTagGroupType>();
        }
        return this.specialCharacterTagGroup;
    }

    /**
     * Gets the value of the characterTagGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the characterTagGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCharacterTagGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CharacterTagGroupType }
     * 
     * 
     */
    public List<CharacterTagGroupType> getCharacterTagGroup() {
        if (characterTagGroup == null) {
            characterTagGroup = new ArrayList<CharacterTagGroupType>();
        }
        return this.characterTagGroup;
    }

    /**
     * Gets the value of the footnoteTagGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the footnoteTagGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFootnoteTagGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FootnoteTagGroupType }
     * 
     * 
     */
    public List<FootnoteTagGroupType> getFootnoteTagGroup() {
        if (footnoteTagGroup == null) {
            footnoteTagGroup = new ArrayList<FootnoteTagGroupType>();
        }
        return this.footnoteTagGroup;
    }

    /**
     * Gets the value of the hyperlinkTagGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hyperlinkTagGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHyperlinkTagGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HyperlinkTagGroupType }
     * 
     * 
     */
    public List<HyperlinkTagGroupType> getHyperlinkTagGroup() {
        if (hyperlinkTagGroup == null) {
            hyperlinkTagGroup = new ArrayList<HyperlinkTagGroupType>();
        }
        return this.hyperlinkTagGroup;
    }

}
