//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:49:43 PM IST 
//


package com.kraft.pim.sap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for F_PROMOTIONAL_ADVERTISEMENT_28_ML complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="F_PROMOTIONAL_ADVERTISEMENT_28_ML">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="F_PROMOTIONAL_ADVERTISEMENTLanguage" type="{}Language" minOccurs="0"/>
 *         &lt;element name="F_PROMOTIONAL_ADVERTISEMENT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="75"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "F_PROMOTIONAL_ADVERTISEMENT_28_ML", propOrder = {
    "fpromotionaladvertisementLanguage",
    "fpromotionaladvertisement"
})
public class FPROMOTIONALADVERTISEMENT28ML {

    @XmlElement(name = "F_PROMOTIONAL_ADVERTISEMENTLanguage")
    @XmlSchemaType(name = "string")
    protected Language fpromotionaladvertisementLanguage;
    @XmlElement(name = "F_PROMOTIONAL_ADVERTISEMENT")
    protected String fpromotionaladvertisement;

    /**
     * Gets the value of the fpromotionaladvertisementLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link Language }
     *     
     */
    public Language getFPROMOTIONALADVERTISEMENTLanguage() {
        return fpromotionaladvertisementLanguage;
    }

    /**
     * Sets the value of the fpromotionaladvertisementLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Language }
     *     
     */
    public void setFPROMOTIONALADVERTISEMENTLanguage(Language value) {
        this.fpromotionaladvertisementLanguage = value;
    }

    /**
     * Gets the value of the fpromotionaladvertisement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPROMOTIONALADVERTISEMENT() {
        return fpromotionaladvertisement;
    }

    /**
     * Sets the value of the fpromotionaladvertisement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPROMOTIONALADVERTISEMENT(String value) {
        this.fpromotionaladvertisement = value;
    }

}
