//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:49:43 PM IST 
//


package com.kraft.pim.sap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_BAR_CODE_TYPES complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_BAR_CODE_TYPES">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="F_BAR_CODE_TYPE_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_BAR_CODE_TYPE_NAME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_BAR_CODE_TYPES", propOrder = {
    "fbarcodetypecode",
    "fbarcodetypename"
})
public class TBARCODETYPES {

    @XmlElement(name = "F_BAR_CODE_TYPE_CODE")
    protected String fbarcodetypecode;
    @XmlElement(name = "F_BAR_CODE_TYPE_NAME")
    protected String fbarcodetypename;

    /**
     * Gets the value of the fbarcodetypecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFBARCODETYPECODE() {
        return fbarcodetypecode;
    }

    /**
     * Sets the value of the fbarcodetypecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFBARCODETYPECODE(String value) {
        this.fbarcodetypecode = value;
    }

    /**
     * Gets the value of the fbarcodetypename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFBARCODETYPENAME() {
        return fbarcodetypename;
    }

    /**
     * Sets the value of the fbarcodetypename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFBARCODETYPENAME(String value) {
        this.fbarcodetypename = value;
    }

}
