//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:49:43 PM IST 
//


package com.kraft.pim.sap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_CAPACITY_GROUP_CODES complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_CAPACITY_GROUP_CODES">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="F_CAPACITY_GROUP_CODE_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_CAPACITY_GROUP_CODE_NAME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_CAPACITY_GROUP_CODES", propOrder = {
    "fcapacitygroupcodecode",
    "fcapacitygroupcodename"
})
public class TCAPACITYGROUPCODES {

    @XmlElement(name = "F_CAPACITY_GROUP_CODE_CODE")
    protected String fcapacitygroupcodecode;
    @XmlElement(name = "F_CAPACITY_GROUP_CODE_NAME")
    protected String fcapacitygroupcodename;

    /**
     * Gets the value of the fcapacitygroupcodecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCAPACITYGROUPCODECODE() {
        return fcapacitygroupcodecode;
    }

    /**
     * Sets the value of the fcapacitygroupcodecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCAPACITYGROUPCODECODE(String value) {
        this.fcapacitygroupcodecode = value;
    }

    /**
     * Gets the value of the fcapacitygroupcodename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCAPACITYGROUPCODENAME() {
        return fcapacitygroupcodename;
    }

    /**
     * Sets the value of the fcapacitygroupcodename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCAPACITYGROUPCODENAME(String value) {
        this.fcapacitygroupcodename = value;
    }

}
