//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:49:43 PM IST 
//


package com.kraft.pim.sap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_CHILD_PACKAGING_RELATIONSHIPS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_CHILD_PACKAGING_RELATIONSHIPS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="F_CHILD_PACKAGING_QUANTITY" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_CHILD_KRAFT_ITEM_CODE" type="{}T_PCL_RECORD" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_CHILD_PACKAGING_RELATIONSHIPS", propOrder = {
    "fchildpackagingquantity",
    "fchildkraftitemcode"
})
public class TCHILDPACKAGINGRELATIONSHIPS {

    @XmlElement(name = "F_CHILD_PACKAGING_QUANTITY")
    protected String fchildpackagingquantity;
    @XmlElement(name = "F_CHILD_KRAFT_ITEM_CODE")
    protected List<TPCLRECORD> fchildkraftitemcode;

    /**
     * Gets the value of the fchildpackagingquantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCHILDPACKAGINGQUANTITY() {
        return fchildpackagingquantity;
    }

    /**
     * Sets the value of the fchildpackagingquantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCHILDPACKAGINGQUANTITY(String value) {
        this.fchildpackagingquantity = value;
    }

    /**
     * Gets the value of the fchildkraftitemcode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fchildkraftitemcode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFCHILDKRAFTITEMCODE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TPCLRECORD }
     * 
     * 
     */
    public List<TPCLRECORD> getFCHILDKRAFTITEMCODE() {
        if (fchildkraftitemcode == null) {
            fchildkraftitemcode = new ArrayList<TPCLRECORD>();
        }
        return this.fchildkraftitemcode;
    }

}
