//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:49:43 PM IST 
//


package com.kraft.pim.sap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_COUNTRIES complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_COUNTRIES">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="F_COUNTRY_CODE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_GDS_COUNTRY_CODE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_COUNTRY_NAME">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_REGION" type="{}T_REGIONS"/>
 *         &lt;element name="F_LANGUAGE" type="{}T_LANGUAGES" maxOccurs="unbounded"/>
 *         &lt;element name="F_INTERFACE_SYSTEMS" type="{}T_SYSTEMS" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_COUNTRIES", propOrder = {
    "fcountrycode",
    "fgdscountrycode",
    "fcountryname",
    "fregion",
    "flanguage",
    "finterfacesystems"
})
public class TCOUNTRIES {

    @XmlElement(name = "F_COUNTRY_CODE", required = true)
    protected String fcountrycode;
    @XmlElement(name = "F_GDS_COUNTRY_CODE", required = true)
    protected String fgdscountrycode;
    @XmlElement(name = "F_COUNTRY_NAME", required = true)
    protected String fcountryname;
    @XmlElement(name = "F_REGION", required = true)
    protected TREGIONS fregion;
    @XmlElement(name = "F_LANGUAGE", required = true)
    protected List<TLANGUAGES> flanguage;
    @XmlElement(name = "F_INTERFACE_SYSTEMS", required = true)
    protected List<TSYSTEMS> finterfacesystems;

    /**
     * Gets the value of the fcountrycode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCOUNTRYCODE() {
        return fcountrycode;
    }

    /**
     * Sets the value of the fcountrycode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCOUNTRYCODE(String value) {
        this.fcountrycode = value;
    }

    /**
     * Gets the value of the fgdscountrycode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFGDSCOUNTRYCODE() {
        return fgdscountrycode;
    }

    /**
     * Sets the value of the fgdscountrycode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFGDSCOUNTRYCODE(String value) {
        this.fgdscountrycode = value;
    }

    /**
     * Gets the value of the fcountryname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCOUNTRYNAME() {
        return fcountryname;
    }

    /**
     * Sets the value of the fcountryname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCOUNTRYNAME(String value) {
        this.fcountryname = value;
    }

    /**
     * Gets the value of the fregion property.
     * 
     * @return
     *     possible object is
     *     {@link TREGIONS }
     *     
     */
    public TREGIONS getFREGION() {
        return fregion;
    }

    /**
     * Sets the value of the fregion property.
     * 
     * @param value
     *     allowed object is
     *     {@link TREGIONS }
     *     
     */
    public void setFREGION(TREGIONS value) {
        this.fregion = value;
    }

    /**
     * Gets the value of the flanguage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flanguage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFLANGUAGE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TLANGUAGES }
     * 
     * 
     */
    public List<TLANGUAGES> getFLANGUAGE() {
        if (flanguage == null) {
            flanguage = new ArrayList<TLANGUAGES>();
        }
        return this.flanguage;
    }

    /**
     * Gets the value of the finterfacesystems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the finterfacesystems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFINTERFACESYSTEMS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TSYSTEMS }
     * 
     * 
     */
    public List<TSYSTEMS> getFINTERFACESYSTEMS() {
        if (finterfacesystems == null) {
            finterfacesystems = new ArrayList<TSYSTEMS>();
        }
        return this.finterfacesystems;
    }

}
