//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:49:43 PM IST 
//


package com.kraft.pim.sap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_GROCERY_SNACKS_INDICATORS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_GROCERY_SNACKS_INDICATORS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="F_GROCERY_SNACK_INDICATOR_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_GROCERY_SNACK_INDICATOR_NAME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_GROCERY_SNACKS_INDICATORS", propOrder = {
    "fgrocerysnackindicatorcode",
    "fgrocerysnackindicatorname"
})
public class TGROCERYSNACKSINDICATORS {

    @XmlElement(name = "F_GROCERY_SNACK_INDICATOR_CODE")
    protected String fgrocerysnackindicatorcode;
    @XmlElement(name = "F_GROCERY_SNACK_INDICATOR_NAME")
    protected String fgrocerysnackindicatorname;

    /**
     * Gets the value of the fgrocerysnackindicatorcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFGROCERYSNACKINDICATORCODE() {
        return fgrocerysnackindicatorcode;
    }

    /**
     * Sets the value of the fgrocerysnackindicatorcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFGROCERYSNACKINDICATORCODE(String value) {
        this.fgrocerysnackindicatorcode = value;
    }

    /**
     * Gets the value of the fgrocerysnackindicatorname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFGROCERYSNACKINDICATORNAME() {
        return fgrocerysnackindicatorname;
    }

    /**
     * Sets the value of the fgrocerysnackindicatorname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFGROCERYSNACKINDICATORNAME(String value) {
        this.fgrocerysnackindicatorname = value;
    }

}
