//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:49:43 PM IST 
//


package com.kraft.pim.sap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_HANDLING_INSTRUCTIONS_CODES complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_HANDLING_INSTRUCTIONS_CODES">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="F_HANDLING_INSTRUCTIONS_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_HANDLING_INSTRUCTIONS_NAME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_HANDLING_INSTRUCTIONS_CODES", propOrder = {
    "fhandlinginstructionscode",
    "fhandlinginstructionsname"
})
public class THANDLINGINSTRUCTIONSCODES {

    @XmlElement(name = "F_HANDLING_INSTRUCTIONS_CODE")
    protected String fhandlinginstructionscode;
    @XmlElement(name = "F_HANDLING_INSTRUCTIONS_NAME")
    protected String fhandlinginstructionsname;

    /**
     * Gets the value of the fhandlinginstructionscode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFHANDLINGINSTRUCTIONSCODE() {
        return fhandlinginstructionscode;
    }

    /**
     * Sets the value of the fhandlinginstructionscode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFHANDLINGINSTRUCTIONSCODE(String value) {
        this.fhandlinginstructionscode = value;
    }

    /**
     * Gets the value of the fhandlinginstructionsname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFHANDLINGINSTRUCTIONSNAME() {
        return fhandlinginstructionsname;
    }

    /**
     * Sets the value of the fhandlinginstructionsname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFHANDLINGINSTRUCTIONSNAME(String value) {
        this.fhandlinginstructionsname = value;
    }

}
