//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:49:43 PM IST 
//


package com.kraft.pim.sap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_MATERIAL_PRICING_GROUPS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_MATERIAL_PRICING_GROUPS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="F_MATERIAL_PRICING_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_MATERIAL_PRICING_NAME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_MATERIAL_PRICING_GROUPS", propOrder = {
    "fmaterialpricingcode",
    "fmaterialpricingname"
})
public class TMATERIALPRICINGGROUPS {

    @XmlElement(name = "F_MATERIAL_PRICING_CODE")
    protected String fmaterialpricingcode;
    @XmlElement(name = "F_MATERIAL_PRICING_NAME")
    protected String fmaterialpricingname;

    /**
     * Gets the value of the fmaterialpricingcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMATERIALPRICINGCODE() {
        return fmaterialpricingcode;
    }

    /**
     * Sets the value of the fmaterialpricingcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMATERIALPRICINGCODE(String value) {
        this.fmaterialpricingcode = value;
    }

    /**
     * Gets the value of the fmaterialpricingname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMATERIALPRICINGNAME() {
        return fmaterialpricingname;
    }

    /**
     * Sets the value of the fmaterialpricingname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMATERIALPRICINGNAME(String value) {
        this.fmaterialpricingname = value;
    }

}
