//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:49:43 PM IST 
//


package com.kraft.pim.sap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_NOURISHING_QUALIFYING_CRITERIA_SSNS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_NOURISHING_QUALIFYING_CRITERIA_SSNS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="F_NOURISHING_QUALIFYING_CRITERIA_SSN_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_NOURISHING_QUALIFYING_CRITERIA_SSN_NAME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_NOURISHING_QUALIFYING_CRITERIA_SSNS", propOrder = {
    "fnourishingqualifyingcriteriassncode",
    "fnourishingqualifyingcriteriassnname"
})
public class TNOURISHINGQUALIFYINGCRITERIASSNS {

    @XmlElement(name = "F_NOURISHING_QUALIFYING_CRITERIA_SSN_CODE")
    protected String fnourishingqualifyingcriteriassncode;
    @XmlElement(name = "F_NOURISHING_QUALIFYING_CRITERIA_SSN_NAME")
    protected String fnourishingqualifyingcriteriassnname;

    /**
     * Gets the value of the fnourishingqualifyingcriteriassncode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFNOURISHINGQUALIFYINGCRITERIASSNCODE() {
        return fnourishingqualifyingcriteriassncode;
    }

    /**
     * Sets the value of the fnourishingqualifyingcriteriassncode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFNOURISHINGQUALIFYINGCRITERIASSNCODE(String value) {
        this.fnourishingqualifyingcriteriassncode = value;
    }

    /**
     * Gets the value of the fnourishingqualifyingcriteriassnname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFNOURISHINGQUALIFYINGCRITERIASSNNAME() {
        return fnourishingqualifyingcriteriassnname;
    }

    /**
     * Sets the value of the fnourishingqualifyingcriteriassnname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFNOURISHINGQUALIFYINGCRITERIASSNNAME(String value) {
        this.fnourishingqualifyingcriteriassnname = value;
    }

}
