//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:49:43 PM IST 
//


package com.kraft.pim.sap;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_PCL_RECORD complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_PCL_RECORD">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="F_STATUS_MDM" type="{}T_STATUSES_MDM" minOccurs="0"/>
 *         &lt;element name="F_MANUFACTURER_NO_PREFIX_CODE" type="{}T_MANUFACTURER_NO_PREFIX_CODES" minOccurs="0"/>
 *         &lt;element name="F_PRODUCT_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_KNAC_14_SUFFIX_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_STATUS_GRID" type="{}T_STATUSES_GRID" minOccurs="0"/>
 *         &lt;element name="F_KRAFT_ITEM_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_GTIN" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_REPLACES_GTIN" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_REPLACED_BY_GTIN" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_KNAC_14" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_CONSUMER_UNIT_FLAG" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Yes"/>
 *               &lt;enumeration value="No"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_ORDERABLE_UNIT_FLAG" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Yes"/>
 *               &lt;enumeration value="No"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_KIC_7" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_UNIT_DESCRIPTOR" type="{}T_UNIT_DESCRIPTORS" minOccurs="0"/>
 *         &lt;element name="F_NEXT_LOWER_LEVEL_UNITS_PER_TRADE_UNIT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_NEXT_LOWER_LEVEL_TRADE_UNITS_PER_LAYER" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_LAYERS_PER_TRADE_UNIT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_PCL_RECORD", propOrder = {
    "fstatusmdm",
    "fmanufacturernoprefixcode",
    "fproductcode",
    "fknac14SUFFIXCODE",
    "fstatusgrid",
    "fkraftitemcode",
    "fgtin",
    "freplacesgtin",
    "freplacedbygtin",
    "fknac14",
    "fconsumerunitflag",
    "forderableunitflag",
    "fkic7",
    "funitdescriptor",
    "fnextlowerlevelunitspertradeunit",
    "fnextlowerleveltradeunitsperlayer",
    "flayerspertradeunit"
})
public class TPCLRECORD {

    @XmlElement(name = "F_STATUS_MDM")
    protected TSTATUSESMDM fstatusmdm;
    @XmlElement(name = "F_MANUFACTURER_NO_PREFIX_CODE")
    protected TMANUFACTURERNOPREFIXCODES fmanufacturernoprefixcode;
    @XmlElement(name = "F_PRODUCT_CODE")
    protected String fproductcode;
    @XmlElement(name = "F_KNAC_14_SUFFIX_CODE")
    protected String fknac14SUFFIXCODE;
    @XmlElement(name = "F_STATUS_GRID")
    protected TSTATUSESGRID fstatusgrid;
    @XmlElement(name = "F_KRAFT_ITEM_CODE")
    protected String fkraftitemcode;
    @XmlElement(name = "F_GTIN")
    protected String fgtin;
    @XmlElement(name = "F_REPLACES_GTIN")
    protected String freplacesgtin;
    @XmlElement(name = "F_REPLACED_BY_GTIN")
    protected String freplacedbygtin;
    @XmlElement(name = "F_KNAC_14")
    protected String fknac14;
    @XmlElement(name = "F_CONSUMER_UNIT_FLAG")
    protected String fconsumerunitflag;
    @XmlElement(name = "F_ORDERABLE_UNIT_FLAG")
    protected String forderableunitflag;
    @XmlElement(name = "F_KIC_7")
    protected String fkic7;
    @XmlElement(name = "F_UNIT_DESCRIPTOR")
    protected TUNITDESCRIPTORS funitdescriptor;
    @XmlElement(name = "F_NEXT_LOWER_LEVEL_UNITS_PER_TRADE_UNIT")
    protected BigInteger fnextlowerlevelunitspertradeunit;
    @XmlElement(name = "F_NEXT_LOWER_LEVEL_TRADE_UNITS_PER_LAYER")
    protected BigInteger fnextlowerleveltradeunitsperlayer;
    @XmlElement(name = "F_LAYERS_PER_TRADE_UNIT")
    protected BigInteger flayerspertradeunit;

    /**
     * Gets the value of the fstatusmdm property.
     * 
     * @return
     *     possible object is
     *     {@link TSTATUSESMDM }
     *     
     */
    public TSTATUSESMDM getFSTATUSMDM() {
        return fstatusmdm;
    }

    /**
     * Sets the value of the fstatusmdm property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSTATUSESMDM }
     *     
     */
    public void setFSTATUSMDM(TSTATUSESMDM value) {
        this.fstatusmdm = value;
    }

    /**
     * Gets the value of the fmanufacturernoprefixcode property.
     * 
     * @return
     *     possible object is
     *     {@link TMANUFACTURERNOPREFIXCODES }
     *     
     */
    public TMANUFACTURERNOPREFIXCODES getFMANUFACTURERNOPREFIXCODE() {
        return fmanufacturernoprefixcode;
    }

    /**
     * Sets the value of the fmanufacturernoprefixcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMANUFACTURERNOPREFIXCODES }
     *     
     */
    public void setFMANUFACTURERNOPREFIXCODE(TMANUFACTURERNOPREFIXCODES value) {
        this.fmanufacturernoprefixcode = value;
    }

    /**
     * Gets the value of the fproductcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPRODUCTCODE() {
        return fproductcode;
    }

    /**
     * Sets the value of the fproductcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPRODUCTCODE(String value) {
        this.fproductcode = value;
    }

    /**
     * Gets the value of the fknac14SUFFIXCODE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFKNAC14SUFFIXCODE() {
        return fknac14SUFFIXCODE;
    }

    /**
     * Sets the value of the fknac14SUFFIXCODE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFKNAC14SUFFIXCODE(String value) {
        this.fknac14SUFFIXCODE = value;
    }

    /**
     * Gets the value of the fstatusgrid property.
     * 
     * @return
     *     possible object is
     *     {@link TSTATUSESGRID }
     *     
     */
    public TSTATUSESGRID getFSTATUSGRID() {
        return fstatusgrid;
    }

    /**
     * Sets the value of the fstatusgrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSTATUSESGRID }
     *     
     */
    public void setFSTATUSGRID(TSTATUSESGRID value) {
        this.fstatusgrid = value;
    }

    /**
     * Gets the value of the fkraftitemcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFKRAFTITEMCODE() {
        return fkraftitemcode;
    }

    /**
     * Sets the value of the fkraftitemcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFKRAFTITEMCODE(String value) {
        this.fkraftitemcode = value;
    }

    /**
     * Gets the value of the fgtin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFGTIN() {
        return fgtin;
    }

    /**
     * Sets the value of the fgtin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFGTIN(String value) {
        this.fgtin = value;
    }

    /**
     * Gets the value of the freplacesgtin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFREPLACESGTIN() {
        return freplacesgtin;
    }

    /**
     * Sets the value of the freplacesgtin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFREPLACESGTIN(String value) {
        this.freplacesgtin = value;
    }

    /**
     * Gets the value of the freplacedbygtin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFREPLACEDBYGTIN() {
        return freplacedbygtin;
    }

    /**
     * Sets the value of the freplacedbygtin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFREPLACEDBYGTIN(String value) {
        this.freplacedbygtin = value;
    }

    /**
     * Gets the value of the fknac14 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFKNAC14() {
        return fknac14;
    }

    /**
     * Sets the value of the fknac14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFKNAC14(String value) {
        this.fknac14 = value;
    }

    /**
     * Gets the value of the fconsumerunitflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCONSUMERUNITFLAG() {
        return fconsumerunitflag;
    }

    /**
     * Sets the value of the fconsumerunitflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCONSUMERUNITFLAG(String value) {
        this.fconsumerunitflag = value;
    }

    /**
     * Gets the value of the forderableunitflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFORDERABLEUNITFLAG() {
        return forderableunitflag;
    }

    /**
     * Sets the value of the forderableunitflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFORDERABLEUNITFLAG(String value) {
        this.forderableunitflag = value;
    }

    /**
     * Gets the value of the fkic7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFKIC7() {
        return fkic7;
    }

    /**
     * Sets the value of the fkic7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFKIC7(String value) {
        this.fkic7 = value;
    }

    /**
     * Gets the value of the funitdescriptor property.
     * 
     * @return
     *     possible object is
     *     {@link TUNITDESCRIPTORS }
     *     
     */
    public TUNITDESCRIPTORS getFUNITDESCRIPTOR() {
        return funitdescriptor;
    }

    /**
     * Sets the value of the funitdescriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TUNITDESCRIPTORS }
     *     
     */
    public void setFUNITDESCRIPTOR(TUNITDESCRIPTORS value) {
        this.funitdescriptor = value;
    }

    /**
     * Gets the value of the fnextlowerlevelunitspertradeunit property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFNEXTLOWERLEVELUNITSPERTRADEUNIT() {
        return fnextlowerlevelunitspertradeunit;
    }

    /**
     * Sets the value of the fnextlowerlevelunitspertradeunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFNEXTLOWERLEVELUNITSPERTRADEUNIT(BigInteger value) {
        this.fnextlowerlevelunitspertradeunit = value;
    }

    /**
     * Gets the value of the fnextlowerleveltradeunitsperlayer property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFNEXTLOWERLEVELTRADEUNITSPERLAYER() {
        return fnextlowerleveltradeunitsperlayer;
    }

    /**
     * Sets the value of the fnextlowerleveltradeunitsperlayer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFNEXTLOWERLEVELTRADEUNITSPERLAYER(BigInteger value) {
        this.fnextlowerleveltradeunitsperlayer = value;
    }

    /**
     * Gets the value of the flayerspertradeunit property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFLAYERSPERTRADEUNIT() {
        return flayerspertradeunit;
    }

    /**
     * Sets the value of the flayerspertradeunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFLAYERSPERTRADEUNIT(BigInteger value) {
        this.flayerspertradeunit = value;
    }

}
