//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:49:43 PM IST 
//


package com.kraft.pim.sap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_PLATFORM_TYPES complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_PLATFORM_TYPES">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="F_PLATFORM_TYPE_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_PLATFORM_TYPE_NAME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_PLATFORM_TYPES", propOrder = {
    "fplatformtypecode",
    "fplatformtypename"
})
public class TPLATFORMTYPES {

    @XmlElement(name = "F_PLATFORM_TYPE_CODE")
    protected String fplatformtypecode;
    @XmlElement(name = "F_PLATFORM_TYPE_NAME")
    protected String fplatformtypename;

    /**
     * Gets the value of the fplatformtypecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPLATFORMTYPECODE() {
        return fplatformtypecode;
    }

    /**
     * Sets the value of the fplatformtypecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPLATFORMTYPECODE(String value) {
        this.fplatformtypecode = value;
    }

    /**
     * Gets the value of the fplatformtypename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPLATFORMTYPENAME() {
        return fplatformtypename;
    }

    /**
     * Sets the value of the fplatformtypename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPLATFORMTYPENAME(String value) {
        this.fplatformtypename = value;
    }

}
