//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:49:43 PM IST 
//


package com.kraft.pim.sap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_PLANT_STATUSES complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_PLANT_STATUSES">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="F_PLANT_STATUS_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_PLANT_STATUS_NAME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_PLANT_STATUSES", propOrder = {
    "fplantstatuscode",
    "fplantstatusname"
})
public class TPLANTSTATUSES {

    @XmlElement(name = "F_PLANT_STATUS_CODE")
    protected String fplantstatuscode;
    @XmlElement(name = "F_PLANT_STATUS_NAME")
    protected String fplantstatusname;

    /**
     * Gets the value of the fplantstatuscode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPLANTSTATUSCODE() {
        return fplantstatuscode;
    }

    /**
     * Sets the value of the fplantstatuscode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPLANTSTATUSCODE(String value) {
        this.fplantstatuscode = value;
    }

    /**
     * Gets the value of the fplantstatusname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPLANTSTATUSNAME() {
        return fplantstatusname;
    }

    /**
     * Sets the value of the fplantstatusname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPLANTSTATUSNAME(String value) {
        this.fplantstatusname = value;
    }

}
