//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:49:43 PM IST 
//


package com.kraft.pim.sap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_PRODUCT_HIERARCHY_CATALYST complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_PRODUCT_HIERARCHY_CATALYST">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="F_PRODUCT_HIERARCHY_CATALYST_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="F_PRODUCT_HIERARCHY_CATALYST_NAME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_PRODUCT_HIERARCHY_CATALYST_CREATE_DATE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_PRODUCT_HIERARCHY_CATALYST_UPDATE_DATE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_PRODUCT_HIERARCHY_CATALYST_UPDATE_BY" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_PRODUCT_HIERARCHY_DELETE_FROM_ECC_FLAG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRODUCT_HIERARCHY_HOLD_FUTURE_DELETE_FLAG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="F_PRODUCT_HIERARCHY_SYNIDCATE_FLIP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="F_PRODUCT_HIERARCHY_SYNIDCATE_FLIP_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="F_PRODUCT_HIERARCHY_SYNIDCATE_RECORD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="F_PRODUCT_HIERARCHY_DELETION_FLAG" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="TRUE"/>
 *               &lt;enumeration value="FALSE"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_PRODUCT_HIERARCHY_CATALYST", propOrder = {
    "fproducthierarchycatalystcode",
    "fproducthierarchycatalystname",
    "fproducthierarchycatalystcreatedate",
    "fproducthierarchycatalystupdatedate",
    "fproducthierarchycatalystupdateby",
    "fproducthierarchydeletefromeccflag",
    "producthierarchyholdfuturedeleteflag",
    "fproducthierarchysynidcateflip",
    "fproducthierarchysynidcateflipdate",
    "fproducthierarchysynidcaterecord",
    "fproducthierarchydeletionflag"
})
public class TPRODUCTHIERARCHYCATALYST {

    @XmlElement(name = "F_PRODUCT_HIERARCHY_CATALYST_CODE")
    protected String fproducthierarchycatalystcode;
    @XmlElement(name = "F_PRODUCT_HIERARCHY_CATALYST_NAME")
    protected String fproducthierarchycatalystname;
    @XmlElement(name = "F_PRODUCT_HIERARCHY_CATALYST_CREATE_DATE")
    protected String fproducthierarchycatalystcreatedate;
    @XmlElement(name = "F_PRODUCT_HIERARCHY_CATALYST_UPDATE_DATE")
    protected String fproducthierarchycatalystupdatedate;
    @XmlElement(name = "F_PRODUCT_HIERARCHY_CATALYST_UPDATE_BY")
    protected String fproducthierarchycatalystupdateby;
    @XmlElement(name = "F_PRODUCT_HIERARCHY_DELETE_FROM_ECC_FLAG", required = true)
    protected String fproducthierarchydeletefromeccflag;
    @XmlElement(name = "PRODUCT_HIERARCHY_HOLD_FUTURE_DELETE_FLAG", required = true)
    protected String producthierarchyholdfuturedeleteflag;
    @XmlElement(name = "F_PRODUCT_HIERARCHY_SYNIDCATE_FLIP", required = true)
    protected String fproducthierarchysynidcateflip;
    @XmlElement(name = "F_PRODUCT_HIERARCHY_SYNIDCATE_FLIP_DATE", required = true)
    protected String fproducthierarchysynidcateflipdate;
    @XmlElement(name = "F_PRODUCT_HIERARCHY_SYNIDCATE_RECORD", required = true)
    protected String fproducthierarchysynidcaterecord;
    @XmlElement(name = "F_PRODUCT_HIERARCHY_DELETION_FLAG")
    protected String fproducthierarchydeletionflag;

    /**
     * Gets the value of the fproducthierarchycatalystcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPRODUCTHIERARCHYCATALYSTCODE() {
        return fproducthierarchycatalystcode;
    }

    /**
     * Sets the value of the fproducthierarchycatalystcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPRODUCTHIERARCHYCATALYSTCODE(String value) {
        this.fproducthierarchycatalystcode = value;
    }

    /**
     * Gets the value of the fproducthierarchycatalystname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPRODUCTHIERARCHYCATALYSTNAME() {
        return fproducthierarchycatalystname;
    }

    /**
     * Sets the value of the fproducthierarchycatalystname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPRODUCTHIERARCHYCATALYSTNAME(String value) {
        this.fproducthierarchycatalystname = value;
    }

    /**
     * Gets the value of the fproducthierarchycatalystcreatedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPRODUCTHIERARCHYCATALYSTCREATEDATE() {
        return fproducthierarchycatalystcreatedate;
    }

    /**
     * Sets the value of the fproducthierarchycatalystcreatedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPRODUCTHIERARCHYCATALYSTCREATEDATE(String value) {
        this.fproducthierarchycatalystcreatedate = value;
    }

    /**
     * Gets the value of the fproducthierarchycatalystupdatedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPRODUCTHIERARCHYCATALYSTUPDATEDATE() {
        return fproducthierarchycatalystupdatedate;
    }

    /**
     * Sets the value of the fproducthierarchycatalystupdatedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPRODUCTHIERARCHYCATALYSTUPDATEDATE(String value) {
        this.fproducthierarchycatalystupdatedate = value;
    }

    /**
     * Gets the value of the fproducthierarchycatalystupdateby property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPRODUCTHIERARCHYCATALYSTUPDATEBY() {
        return fproducthierarchycatalystupdateby;
    }

    /**
     * Sets the value of the fproducthierarchycatalystupdateby property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPRODUCTHIERARCHYCATALYSTUPDATEBY(String value) {
        this.fproducthierarchycatalystupdateby = value;
    }

    /**
     * Gets the value of the fproducthierarchydeletefromeccflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPRODUCTHIERARCHYDELETEFROMECCFLAG() {
        return fproducthierarchydeletefromeccflag;
    }

    /**
     * Sets the value of the fproducthierarchydeletefromeccflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPRODUCTHIERARCHYDELETEFROMECCFLAG(String value) {
        this.fproducthierarchydeletefromeccflag = value;
    }

    /**
     * Gets the value of the producthierarchyholdfuturedeleteflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRODUCTHIERARCHYHOLDFUTUREDELETEFLAG() {
        return producthierarchyholdfuturedeleteflag;
    }

    /**
     * Sets the value of the producthierarchyholdfuturedeleteflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRODUCTHIERARCHYHOLDFUTUREDELETEFLAG(String value) {
        this.producthierarchyholdfuturedeleteflag = value;
    }

    /**
     * Gets the value of the fproducthierarchysynidcateflip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPRODUCTHIERARCHYSYNIDCATEFLIP() {
        return fproducthierarchysynidcateflip;
    }

    /**
     * Sets the value of the fproducthierarchysynidcateflip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPRODUCTHIERARCHYSYNIDCATEFLIP(String value) {
        this.fproducthierarchysynidcateflip = value;
    }

    /**
     * Gets the value of the fproducthierarchysynidcateflipdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPRODUCTHIERARCHYSYNIDCATEFLIPDATE() {
        return fproducthierarchysynidcateflipdate;
    }

    /**
     * Sets the value of the fproducthierarchysynidcateflipdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPRODUCTHIERARCHYSYNIDCATEFLIPDATE(String value) {
        this.fproducthierarchysynidcateflipdate = value;
    }

    /**
     * Gets the value of the fproducthierarchysynidcaterecord property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPRODUCTHIERARCHYSYNIDCATERECORD() {
        return fproducthierarchysynidcaterecord;
    }

    /**
     * Sets the value of the fproducthierarchysynidcaterecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPRODUCTHIERARCHYSYNIDCATERECORD(String value) {
        this.fproducthierarchysynidcaterecord = value;
    }

    /**
     * Gets the value of the fproducthierarchydeletionflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPRODUCTHIERARCHYDELETIONFLAG() {
        return fproducthierarchydeletionflag;
    }

    /**
     * Sets the value of the fproducthierarchydeletionflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPRODUCTHIERARCHYDELETIONFLAG(String value) {
        this.fproducthierarchydeletionflag = value;
    }

}
