//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:49:43 PM IST 
//


package com.kraft.pim.sap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_SALES_STATUS_DATA complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_SALES_STATUS_DATA">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="F_DISTRIBUTION_CHANNEL_CODE" type="{}T_DISTRIBUTION_CHANNELS"/>
 *         &lt;element name="F_SALES_STATUS_CODE" type="{}T_SALES_STATUSES"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_SALES_STATUS_DATA", propOrder = {
    "fdistributionchannelcode",
    "fsalesstatuscode"
})
public class TSALESSTATUSDATA {

    @XmlElement(name = "F_DISTRIBUTION_CHANNEL_CODE", required = true)
    protected TDISTRIBUTIONCHANNELS fdistributionchannelcode;
    @XmlElement(name = "F_SALES_STATUS_CODE", required = true)
    protected TSALESSTATUSES fsalesstatuscode;

    /**
     * Gets the value of the fdistributionchannelcode property.
     * 
     * @return
     *     possible object is
     *     {@link TDISTRIBUTIONCHANNELS }
     *     
     */
    public TDISTRIBUTIONCHANNELS getFDISTRIBUTIONCHANNELCODE() {
        return fdistributionchannelcode;
    }

    /**
     * Sets the value of the fdistributionchannelcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDISTRIBUTIONCHANNELS }
     *     
     */
    public void setFDISTRIBUTIONCHANNELCODE(TDISTRIBUTIONCHANNELS value) {
        this.fdistributionchannelcode = value;
    }

    /**
     * Gets the value of the fsalesstatuscode property.
     * 
     * @return
     *     possible object is
     *     {@link TSALESSTATUSES }
     *     
     */
    public TSALESSTATUSES getFSALESSTATUSCODE() {
        return fsalesstatuscode;
    }

    /**
     * Sets the value of the fsalesstatuscode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSALESSTATUSES }
     *     
     */
    public void setFSALESSTATUSCODE(TSALESSTATUSES value) {
        this.fsalesstatuscode = value;
    }

}
