//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:49:43 PM IST 
//


package com.kraft.pim.sap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_SHELF_LIFE_UOMS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_SHELF_LIFE_UOMS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="F_SHELF_LIFE_UOM_CODE">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="F_SHELF_LIFE_UOM_CODE_ML" type="{}F_SHELF_LIFE_UOM_CODE_53_ML" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="F_SHELF_LIFE_UOM_NAME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_SHELF_LIFE_UOMS", propOrder = {
    "fshelflifeuomcode",
    "fshelflifeuomname"
})
public class TSHELFLIFEUOMS {

    @XmlElement(name = "F_SHELF_LIFE_UOM_CODE", required = true)
    protected TSHELFLIFEUOMS.FSHELFLIFEUOMCODE fshelflifeuomcode;
    @XmlElement(name = "F_SHELF_LIFE_UOM_NAME")
    protected String fshelflifeuomname;

    /**
     * Gets the value of the fshelflifeuomcode property.
     * 
     * @return
     *     possible object is
     *     {@link TSHELFLIFEUOMS.FSHELFLIFEUOMCODE }
     *     
     */
    public TSHELFLIFEUOMS.FSHELFLIFEUOMCODE getFSHELFLIFEUOMCODE() {
        return fshelflifeuomcode;
    }

    /**
     * Sets the value of the fshelflifeuomcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSHELFLIFEUOMS.FSHELFLIFEUOMCODE }
     *     
     */
    public void setFSHELFLIFEUOMCODE(TSHELFLIFEUOMS.FSHELFLIFEUOMCODE value) {
        this.fshelflifeuomcode = value;
    }

    /**
     * Gets the value of the fshelflifeuomname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFSHELFLIFEUOMNAME() {
        return fshelflifeuomname;
    }

    /**
     * Sets the value of the fshelflifeuomname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFSHELFLIFEUOMNAME(String value) {
        this.fshelflifeuomname = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="F_SHELF_LIFE_UOM_CODE_ML" type="{}F_SHELF_LIFE_UOM_CODE_53_ML" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fshelflifeuomcodeml"
    })
    public static class FSHELFLIFEUOMCODE {

        @XmlElement(name = "F_SHELF_LIFE_UOM_CODE_ML", required = true)
        protected List<FSHELFLIFEUOMCODE53ML> fshelflifeuomcodeml;

        /**
         * Gets the value of the fshelflifeuomcodeml property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fshelflifeuomcodeml property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFSHELFLIFEUOMCODEML().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FSHELFLIFEUOMCODE53ML }
         * 
         * 
         */
        public List<FSHELFLIFEUOMCODE53ML> getFSHELFLIFEUOMCODEML() {
            if (fshelflifeuomcodeml == null) {
                fshelflifeuomcodeml = new ArrayList<FSHELFLIFEUOMCODE53ML>();
            }
            return this.fshelflifeuomcodeml;
        }

    }

}
