//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:49:43 PM IST 
//


package com.kraft.pim.sap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_SUITABILITY_INFORMATION_DATA complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_SUITABILITY_INFORMATION_DATA">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="F_SUITABILITY_INFORMATION_TYPE" type="{}T_SUITABILITY_INFORMATION_TYPES" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="F_SUITABILITY_INFORMATION_CERTIFYING_AGENCY" type="{}T_SUITABILITY_CERTIFYING_AGENCIES" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="F_SUITABILITY_INFORMATION_INDICATOR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_SUITABILITY_INFORMATION_DOCUMENT_NUMBER" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_SUITABILITY_INFORMATION_ORGANIC_CATEGORY" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_SUITABILITY_INFORMATION_SYMBOL" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_SUITABILITY_INFORMATION_DATA", propOrder = {
    "fsuitabilityinformationtype",
    "fsuitabilityinformationcertifyingagency",
    "fsuitabilityinformationindicator",
    "fsuitabilityinformationdocumentnumber",
    "fsuitabilityinformationorganiccategory",
    "fsuitabilityinformationsymbol"
})
public class TSUITABILITYINFORMATIONDATA {

    @XmlElement(name = "F_SUITABILITY_INFORMATION_TYPE")
    protected List<TSUITABILITYINFORMATIONTYPES> fsuitabilityinformationtype;
    @XmlElement(name = "F_SUITABILITY_INFORMATION_CERTIFYING_AGENCY")
    protected List<TSUITABILITYCERTIFYINGAGENCIES> fsuitabilityinformationcertifyingagency;
    @XmlElement(name = "F_SUITABILITY_INFORMATION_INDICATOR")
    protected String fsuitabilityinformationindicator;
    @XmlElement(name = "F_SUITABILITY_INFORMATION_DOCUMENT_NUMBER")
    protected String fsuitabilityinformationdocumentnumber;
    @XmlElement(name = "F_SUITABILITY_INFORMATION_ORGANIC_CATEGORY")
    protected String fsuitabilityinformationorganiccategory;
    @XmlElement(name = "F_SUITABILITY_INFORMATION_SYMBOL")
    protected String fsuitabilityinformationsymbol;

    /**
     * Gets the value of the fsuitabilityinformationtype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fsuitabilityinformationtype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFSUITABILITYINFORMATIONTYPE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TSUITABILITYINFORMATIONTYPES }
     * 
     * 
     */
    public List<TSUITABILITYINFORMATIONTYPES> getFSUITABILITYINFORMATIONTYPE() {
        if (fsuitabilityinformationtype == null) {
            fsuitabilityinformationtype = new ArrayList<TSUITABILITYINFORMATIONTYPES>();
        }
        return this.fsuitabilityinformationtype;
    }

    /**
     * Gets the value of the fsuitabilityinformationcertifyingagency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fsuitabilityinformationcertifyingagency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFSUITABILITYINFORMATIONCERTIFYINGAGENCY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TSUITABILITYCERTIFYINGAGENCIES }
     * 
     * 
     */
    public List<TSUITABILITYCERTIFYINGAGENCIES> getFSUITABILITYINFORMATIONCERTIFYINGAGENCY() {
        if (fsuitabilityinformationcertifyingagency == null) {
            fsuitabilityinformationcertifyingagency = new ArrayList<TSUITABILITYCERTIFYINGAGENCIES>();
        }
        return this.fsuitabilityinformationcertifyingagency;
    }

    /**
     * Gets the value of the fsuitabilityinformationindicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFSUITABILITYINFORMATIONINDICATOR() {
        return fsuitabilityinformationindicator;
    }

    /**
     * Sets the value of the fsuitabilityinformationindicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFSUITABILITYINFORMATIONINDICATOR(String value) {
        this.fsuitabilityinformationindicator = value;
    }

    /**
     * Gets the value of the fsuitabilityinformationdocumentnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFSUITABILITYINFORMATIONDOCUMENTNUMBER() {
        return fsuitabilityinformationdocumentnumber;
    }

    /**
     * Sets the value of the fsuitabilityinformationdocumentnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFSUITABILITYINFORMATIONDOCUMENTNUMBER(String value) {
        this.fsuitabilityinformationdocumentnumber = value;
    }

    /**
     * Gets the value of the fsuitabilityinformationorganiccategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFSUITABILITYINFORMATIONORGANICCATEGORY() {
        return fsuitabilityinformationorganiccategory;
    }

    /**
     * Sets the value of the fsuitabilityinformationorganiccategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFSUITABILITYINFORMATIONORGANICCATEGORY(String value) {
        this.fsuitabilityinformationorganiccategory = value;
    }

    /**
     * Gets the value of the fsuitabilityinformationsymbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFSUITABILITYINFORMATIONSYMBOL() {
        return fsuitabilityinformationsymbol;
    }

    /**
     * Sets the value of the fsuitabilityinformationsymbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFSUITABILITYINFORMATIONSYMBOL(String value) {
        this.fsuitabilityinformationsymbol = value;
    }

}
