//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:49:43 PM IST 
//


package com.kraft.pim.sap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_TRANSPORTATION_GROUPS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_TRANSPORTATION_GROUPS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="F_TRANSPORTATION_GROUP_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="F_TRANSPORTATION_GROUP_NAME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_TRANSPORTATION_GROUPS", propOrder = {
    "ftransportationgroupcode",
    "ftransportationgroupname"
})
public class TTRANSPORTATIONGROUPS {

    @XmlElement(name = "F_TRANSPORTATION_GROUP_CODE")
    protected String ftransportationgroupcode;
    @XmlElement(name = "F_TRANSPORTATION_GROUP_NAME")
    protected String ftransportationgroupname;

    /**
     * Gets the value of the ftransportationgroupcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFTRANSPORTATIONGROUPCODE() {
        return ftransportationgroupcode;
    }

    /**
     * Sets the value of the ftransportationgroupcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFTRANSPORTATIONGROUPCODE(String value) {
        this.ftransportationgroupcode = value;
    }

    /**
     * Gets the value of the ftransportationgroupname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFTRANSPORTATIONGROUPNAME() {
        return ftransportationgroupname;
    }

    /**
     * Sets the value of the ftransportationgroupname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFTRANSPORTATIONGROUPNAME(String value) {
        this.ftransportationgroupname = value;
    }

}
